### PR TITLE
Added: option to use the jsonrpccommand params in the stub filenames

### PR DESCRIPTION
**Pull request by MarcelRoozekrans**
### Functional description

Added option to the jsonrpccommand implementation to use the params to get a more fine grained files especially for settings.getSettingValue

### Reasoning

Couldn't make settings.getSettingValue to work with current implementation

### Technical description

- Check if there are params available
- string.join the values into the filename

### CODE REVIEW

**Comment by basrieter** [comment]
Great suggestion! I like it. Only issue I now see is that in some cases I don't care for the parameters and just always want to return the same response. Or you want a "catch-all" for a RPC method.

So I would suggest this approach:

1. check for a file with the parameters: 
    - if found use that and return the contents
2. if not found, check for the a file without the parameters, 
   - if found, use that one and return the contents
3. else return the default OK message.

So your code is option 1 (but an `os.path.isfile()` check needs to be added). Option 2 was the one already in place so was option 3.

**Comment by MarcelRoozekrans** [comment]
@basrieter made it a folder if there are params, this way the param files are group and more easy to read.

**Comment by MarcelRoozekrans** [comment]
Hmm, found a bug inside the params dict there could be lists.

**Comment by MarcelRoozekrans** [comment]
OK, made a new implementation, the json files can have multiple request and responses. The logic now tries to match a request if not found it will fallback to the default.

**Pull request closed without merging**
