### PR TITLE
Add default parameters to Keyboard class constructor

### PR DESCRIPTION
**Pull request by michaelarnauts**
### Reasoning

The `Keyboard` constructor was missing default parameters.

### CODE REVIEW

**Comment by basrieter** [comment]
Indeed. I see the correct naming should be: `default, heading, hidden`, not `line, heading, hidden`. Could you perhaps also change that?

**Comment by michaelarnauts** [comment]
Are you sure? The docs seem to mention line in the constructor: https://codedocs.xyz/xbmc/xbmc/class_x_b_m_c_addon_1_1xbmc_1_1_keyboard.html

**Comment by basrieter** [comment]
> Are you sure? The docs seem to mention line in the constructor: https://codedocs.xyz/xbmc/xbmc/class_x_b_m_c_addon_1_1xbmc_1_1_keyboard.html

They seem to have different information: 

https://codedocs.xyz/xbmc/xbmc/group__python__keyboard.html

Let me ask in Team Kodi.

**Comment by basrieter** [comment]
The parameter should be ’line'. The docs need to be updated. So this PR is ok.

**Review by basrieter — APPROVED** [review]

**Comment by basrieter** [comment]
v0.0.5 is now at https://pypi.org/project/sakee/

**Pull request merged**
