### PR TITLE
Added setup.py

### PR DESCRIPTION
**Pull request by MarcelRoozekrans**
### Functional description

Added setup.py to the Saké project.

### Reasoning

This way we can add Saké as a git package in the requirements.txt

### Technical description

Added the setup.py, could find any versioning in this project.
Maybe thats houdl be added aswell te keep track of versions.

### CODE REVIEW

**Comment by basrieter** [comment]
Thanks for this!  I am reading up on how to properly get it into PyPi. I added a test package here https://test.pypi.org/project/sake/. Perhaps you could verify that? I still need to include the `jsonrcpcommands` folder somehow.

**Comment by MarcelRoozekrans** [comment]
> Thanks for this! I am reading up on how to properly get it into PyPi. I added a test package here https://test.pypi.org/project/sake/. Perhaps you could verify that? I still need to include the `jsonrcpcommands` folder somehow.

Very nice ! Looking for a good kodi mock !

There are some encoding issues with the é see:
image

**Comment by MarcelRoozekrans** [comment]
@basrieter Btw. There is allready a package with the sake id in prod PyPi:
https://pypi.org/project/sake/

**Comment by basrieter** [comment]
Yes, I noticed that. The setup.py needs tweaking. The version is a string:

```
version="0.1.1",
```

And the encoding of the README.md is missing:

```
    long_description=open(os.path.join(project_dir, 'README.md'), encoding='utf-8').read(),
    long_description_content_type="text/markdown",
```

I also added this to the .gitignore

```
build/*
dist/*
*.egg-info/*
```

**Comment by MarcelRoozekrans** [comment]
> Yes, I noticed that. The setup.py needs tweaking. The version is a string:
> 
> ```
> version="0.1.1",
> ```
> 
> And the encoding of the README.md is missing:
> 
> ```
>     long_description=open(os.path.join(project_dir, 'README.md'), encoding='utf-8').read(),
>     long_description_content_type="text/markdown",
> ```
> 
> I also added this to the .gitignore
> 
> ```
> build/*
> dist/*
> *.egg-info/*
> ```

I'm quitte new to python and the package life cycle. Added this setup.py worked from my fork.

Tested the package and it installs find on py3.x but I have issues with py2.7
image

**Comment by basrieter** [comment]
Ok, I updated the setup.py. Can you try again with version 0.1.2?

**Comment by MarcelRoozekrans** [comment]
again, 

image

**Comment by basrieter** [comment]
Please try: https://test.pypi.org/project/sake/0.1.5

**Comment by MarcelRoozekrans** [comment]
> Please try: https://test.pypi.org/project/sake/0.1.5

Yes ! this works perfectly

**Comment by basrieter** [comment]
I choose a slightly different package name to prevent the collision with the original `sake` package: https://pypi.org/project/sakee/0.0.1.dev1/

**Comment by basrieter** [comment]
Because I had to change some stuff in the setup.py and move some RPC responses around, I can't merge this PR. But I do want to thank you for initiating it. Thanks to you `pip install sakee` will now work:

https://pypi.org/project/sakee/

**Pull request closed without merging**
